scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: close_range_filter
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        lower_threshold: 0.13 # m
        upper_threshold: 100000.0
        lower_replacement_value: .inf
        upper_replacement_value: .inf
        invert: true
