scan_to_scan_filter_chain:
  ros__parameters:
    tf_message_filter_target_frame: lidar
    use_message_filter: false
    transform_tolerance: 1
    use_sim_time: true
    filter1:
      name: robot_head_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: head
        # min_x: -0.10
        # max_x: 0.10
        # min_y: -0.07
        # max_y: 0.07
        # min_z: 0
        # max_z: 0.2
        min_x: -0.30
        max_x: 0.30
        min_y: -0.30
        max_y: 0.30
        min_z: -0.50
        max_z: 0.50
