async_slam_toolbox_node:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSED_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    odom_frame: odom
    base_frame: root
    map_frame: map

    use_odometry: true
    pub_map_to_odom: true
    pub_map_odom_transform: true

    minimum_time_interval: 0.05
    max_laser_range: 20.0
    minimum_travel_distance: 0.02
    minimum_travel_heading: 0.02
    
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_similarity_score: 0.3
